services:
  - type: web
    name: sdas-ml-inference-service
    env: python
    rootDir: ml_service
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: TF_ENABLE_ONEDNN_OPTS
        value: "0"
